WebApp/Controllers/Categorie_materielController.cs
using Domain;
using Log;
using Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace WebApp.Controllers
    {
        public class Categorie_materielController : Controller
        {
            private ICategorie_materielService db = new Categorie_materielService();
            // GET: Categorie_materiel
            public ActionResult Index()
            {
                return View();
            }

            public ActionResult GetCategorie_materiel()
            {
                var Categorie_materiel = db.GetCategorie_materiels();
                return View(Categorie_materiel);
            }
            // GET: Categorie_materiel/Details/5
            public ActionResult Details(int Id_categorie)
            {
                try
                {

                    var archive = BissInventaireEntities.Instance.Categorie_materiel.Find(Id_categorie);

                    return View(archive);
                }
                catch (Exception ex)
                {


                    LogThread.WriteLine(ex.Message);
                    return RedirectToAction("Index", "Error");
                }

            }

            // GET: Categorie_materiel/Create
            public ActionResult CreateCategorie_materiel()
            {
                return View();
            }

            // POST: Categorie_materiel/Create
            [HttpPost]
            public ActionResult CreateCategorie_materiel(Categorie_materiel Catm, FormCollection collection)
            {
                try
                {
                    BissInventaireEntities.Instance.Categorie_materiel.Add(Catm);
                    BissInventaireEntities.Instance.SaveChanges();
                    return RedirectToAction("GetCategorie_materiel");
                }
                catch (Exception ex)
                {
                    LogThread.WriteLine(ex.Message);
                    return RedirectToAction("Index", "Error");
                }
            }


        public ActionResult EditCategorie_materiel(int id)
        {
            var cat = db.GetCategorie_materiel(id);
            return View(cat);
        }

        // POST: Categorie_materiel/Create
        [HttpPost]
        public ActionResult EditCategorie_materiel(Categorie_materiel Catm)
        {
            try
            {
                db.UpdateCategorie_materielDetached(Catm);
               db.SaveCategorie_materiel();
                return RedirectToAction("GetCategorie_materiel");
            }
            catch (Exception ex)
            {
                LogThread.WriteLine(ex.Message);
                return RedirectToAction("Index", "Error");
            }
        }

        // GET: Categorie_materiel/Edit/5
        public ActionResult Edit(int Id_categorie)
            {
                return View();
            }

            // POST: Categorie_materiel/Edit/5
            [HttpPost]
            public ActionResult Edit(int Id_categorie, FormCollection collection)
            {
                try
                {
                    // TODO: Add update logic here

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }

            // GET: Categorie_materiel/Delete/5
            public ActionResult Delete(int Id_categorie)
            {
                return View();
            }

            // POST: Categorie_materiel/Delete/5
            [HttpPost]
            public ActionResult Delete(int Id_categorie, FormCollection collection)
            {
                try
                {
                    // TODO: Add delete logic here

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }
        }
    }

WebApp/Views/Categorie_materiel/CreateCategorie_materiel.cshtml
@model Domain.Categorie_materiel


<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-title">
                Ajout de categorie materiel
            </div>
            <div class="panel-body">



                <div class="panel panel-default">

                    @using (@Html.BeginForm("CreateCategorie_materiel", "Categorie_materiel", FormMethod.Post,
new { @id = "frmId", @class = "fieldset-form" }))
                    {

                        <div class="form-horizontal">
                            <h4>Categorie materiel</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                          
                            <div class="form-group">
                                <label class="control-label col-lg-4">Nom categorie  </label>
                                <div class="col-lg-6">
                                    @Html.TextBoxFor(model => model.libelle, new { @class = "form-control", required = "" })
                                    @Html.ValidationMessageFor(model => model.libelle, String.Empty, new { @class = "test" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-lg-4">Description  </label>
                                <div class="col-lg-6">
                                    @Html.TextBoxFor(model => model.Description, new { @class = "form-control", required = "" })
                                    @Html.ValidationMessageFor(model => model.Description, String.Empty, new { @class = "test" })
                                </div>
                            </div>

                        </div>
                        <div style="text-align: center;">
                            <input type="submit" value="Valider" class="btn btn-default" />

                            <button type="reset" class="btn btn-white">Annuler</button>

                        </div>

                    }


                </div>

                <div>
                    @Html.ActionLink("Afficher la liste des categories materiels", "GetCategorie_materiel")
                </div>

            </div>
        </div>
    </div>
</div>

WebApp/Views/Categorie_materiel/EditCategorie_materiel.cshtml
@model Domain.Categorie_materiel


<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-title">
                Ajout de categorie materiel
            </div>
            <div class="panel-body">



                <div class="panel panel-default">


                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <h4>Categorie_materiel</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.Id_categorie)

                            <div class="form-group">
                                <label class="control-label col-lg-4">Nom categorie  </label>
                                <div class="col-lg-6">
                                    @Html.TextBoxFor(model => model.libelle, new { @class = "form-control", required = "" })
                                    @Html.ValidationMessageFor(model => model.libelle, String.Empty, new { @class = "test" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-lg-4">Description  </label>
                                <div class="col-lg-6">
                                    @Html.TextBoxFor(model => model.Description, new { @class = "form-control", required = "" })
                                    @Html.ValidationMessageFor(model => model.Description, String.Empty, new { @class = "test" })
                                </div>
                            </div>

                        </div>
                        <div style="text-align: center;">
                            <input type="submit" value="Valider" class="btn btn-default" />

                            <button type="reset" class="btn btn-white">Annuler</button>

                        </div>
                    }

                </div>

                <div>
                    @Html.ActionLink("Afficher la liste des categories materiels", "GetCategorie_materiel")
                </div>

            </div>
        </div>
    </div>
</div>

WebApp/Views/Categorie_materiel/GetCategorie_materiel.cshtml
@model IEnumerable<Domain.Categorie_materiel>

@{
    ViewBag.Title = "GetCategorie_materiel";
}

<h2>Liste des categories materiels</h2>


<!-- Start Row -->
<div class="row">
    <!-- Start Panel -->
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-title">
            
            </div>
            <div class="panel-body table-responsive">
                <table id="example0" class="table display">
                    <thead>
                        <tr>
                           
                            <th>Nom categorie</th>
                            <th>Description</th>
                            <th>Action</th>
                        </tr>
                    </thead>

                    <tfoot>
                        <tr>
                         
                            <th>Nom categorie</th>
                             <th>Description</th>
                            <th>Action</th>

                        </tr>
                    </tfoot>

                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                            
                                <td class="center">@item.libelle</td>
                                <td class="center">@item.Description </td>


                                <td>

                                    <a href="@Url.Action("EditCategorie_materiel", new { id = item.Id_categorie })">&nbsp;<i class="fa fa-edit" title="Modifer"></i></a>
                                     </td>

                            </tr>


                        }
                    </tbody>
                </table>
                <br /><p>
                    @Html.ActionLink("Ajouter une nouvelle Categorie", "CreateCategorie_materiel")
                </p>

            </div>
        </div>
    </div>


</div>





<script>
    $(document).tooltip();
</script>