WebApp/Controllers/ImportExportController.cs
using Domain;
using Microsoft.AspNet.Identity;
using Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Windows.Forms;
using Exel = Microsoft.Office.Interop.Excel;

namespace WebApp.Controllers
{
    public class ImportExportController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Succes()
        {
            return View();
        }

        //public ActionResult Import(HttpPostedFileBase excelfile)
        //{
        //    if (excelfile==null)
        //    {
        //        ViewBag.Error = "Selectionner un fichier Excel SVP !!!";
        //        return View("Index");
        //    }
        //    else
        //    {
        //        if (excelfile.FileName.EndsWith("xls") || excelfile.FileName.EndsWith("xlsx"))
        //        {
        //            string path = Server.MapPath("~/Content/UploadedFolder/" + excelfile.FileName);
        //            if (System.IO.File.Exists(path))
        //                  System.IO.File.Delete(path);
        //            excelfile.SaveAs(path);
        //            Exel.Application app = new Exel.Application();
        //            Exel.Workbook book = app.Workbooks.Open(path);
        //            Exel.Worksheet sheet = book.ActiveSheet;
        //            Exel.Range range = sheet.UsedRange;
        //            List<AtbDataTest> list = new List<AtbDataTest>();
        //            for (int row = 1; row < range.Rows.Count; row++)
        //            {
        //                AtbDataTest NewUpload = new AtbDataTest();
        //               NewUpload.Marque = ((Exel.Range)range.Cells[row, 1]).Text;
        //                NewUpload.Num_serie = ((Exel.Range)range.Cells[row, 2]).Text;
        //                //NewUpload.Categorie = ((Exel.Range)range.Cells[row, 3]).Text;
        //                //NewUpload.Modele = ((Exel.Range)range.Cells[row, 4]).Text;

        //                //NewUpload.Marque = ((Exel.Range)range.Cells[row, 5]).Text;
        //                //NewUpload.Statut = ((Exel.Range)range.Cells[row, 6]).Text;
        //                //NewUpload.Fin_garantie = ((Exel.Range)range.Cells[row, 7]).Text;

        //                //NewUpload.Localisation_dernier = ((Exel.Range)range.Cells[row, 8]).Text;
        //                //NewUpload.Entite_dernier = ((Exel.Range)range.Cells[row, 9]).Text;
        //                //NewUpload.Date_inventaire = ((Exel.Range)range.Cells[row, 10]).Text;
        //                //NewUpload.Date_installation = ((Exel.Range)range.Cells[row, 11]).Text;
        //                //NewUpload.Localisation_complet = ((Exel.Range)range.Cells[row, 12]).Text;
        //                list.Add(NewUpload);

        //            }
        //            ViewBag.list = list;
        //            return View("Succes");
        //        }
        //        else {
        //            ViewBag.Error = "Selectionner un fichier Excel SVP !!!";
        //            return View("Index");

        //             }

        //    }
        //}




        [HttpPost, ActionName("SaveUploadedFile")]
        public ActionResult SaveUploadedFile(string id)
        {
            bool isSavedSuccessfully = true;
            string fName = "";
            string fileName1 = "";
            string fileExtension = "";
            string pathFile = "";
            DataTable ds = new DataTable();
            try
            {
                foreach (string fileName in Request.Files)
                {
                    HttpPostedFileBase file = Request.Files[fileName];

                    fName = file.FileName;
                    fileExtension = System.IO.Path.GetExtension(Request.Files["file"].FileName);
                    if (file != null && file.ContentLength > 0 && (file.FileName.EndsWith("xls") || file.FileName.EndsWith("xlsx")))
                    {
                        var originalDirectory = new DirectoryInfo(string.Format("{0}Fichiers", Server.MapPath(@"\")));
                        string pathString = System.IO.Path.Combine(originalDirectory.ToString(), "Exels");
                        fileName1 = Path.GetFileName(file.FileName);
                        bool isExists = System.IO.Directory.Exists(pathString);
                        if (!isExists)
                            System.IO.Directory.CreateDirectory(pathString);
                        pathFile = string.Format("{0}\\{1}", pathString, file.FileName);
                        file.SaveAs(pathFile);
                    }
                    else
                    {
                        ViewBag.Error = "Selectionner un fichier Excel SVP !!!";
                        return View("Index");
                    }


                }
            }
            catch (Exception ex)
            {
                isSavedSuccessfully = false;
            }

            if (isSavedSuccessfully)
            {
                List<AtbDataTest> list = new List<AtbDataTest>();


                ds = ExcelParser.Instance.ExcelParserToDataTable(pathFile, null);
                foreach (DataRow row in ds.Rows)
                {
                    AtbDataTest catalogue = new AtbDataTest();

                    catalogue.Code_materiel = Convert.ToInt32(row["Code matériel "]);

                    catalogue.Num_serie = row["N° de série "].ToString();
                    catalogue.Categorie = row["Catégorie "].ToString();
                    catalogue.Modele = row["Modèle "].ToString();
                    catalogue.Marque = row["Marque "].ToString();
                    catalogue.Statut = row["Statut "].ToString();
                    catalogue.Fin_garantie = row["Fin de garantie "].ToString();
                    catalogue.Localisation_dernier = row["Localisation (dernier niveau) "].ToString();

                    catalogue.Entite_dernier = row["Entité (dernier niveau) "].ToString();
                    catalogue.Date_inventaire = row["Date inventaire "].ToString();
                    catalogue.Date_installation = row["Date d'installation "].ToString();
                    catalogue.Localisation_complet = row["Localisation (complet) "].ToString();

                    catalogue.Entite_complet = row["Entité (complet) "].ToString();
                    //catalogue.Code_materiel.ToString() = Code;
                    list.Add(catalogue);
                    BissInventaireEntities.Instance.AtbDataTest.Add(catalogue);

                    BissInventaireEntities.Instance.SaveChanges();
                }

                Session["Tesst"] = list.ToList();

                return View("Create1");
            }
            return HttpNotFound();
        }

        public ActionResult Create1(AtbDataTest customer)
        {

            return View();
        }
        // GET: ImportExport
        public void ExportToExel()
        {
            var grid = new GridView();
            var inv = BissInventaireEntities.Instance.AtbDataTest.ToList();
            grid.DataSource = inv;
            grid.DataBind();
            Response.ClearContent();
            String DateExp = DateTime.Now.ToString();
            Response.AddHeader("content-disposition", "attachment;filename=InventaireList_" + DateExp + ".xls");
            Response.ContentType = "text/excel";
            StringWriter sw = new StringWriter();
            HtmlTextWriter htmltexxt = new HtmlTextWriter(sw);
            grid.RenderControl(htmltexxt);
            Response.Write(sw.ToString());
            Response.End();


        }
        public void ExportToCSV()
        {
            StringWriter sw = new StringWriter();
            sw.WriteLine("\"Code materiel\",\"Num de serie\",\"Categorie\",\"Modele\",\"Marque\",\"Statut\",\"Date inventaire\",\"Date Installation\",\"Localisation\"");
            Response.ClearContent();
            String DateExp = DateTime.Now.ToString();
            Response.AddHeader("content-disposition", "attachment;filename=InventaireList_" + DateExp + ".csv");
            Response.ContentType = "text/csv";
            var inv = BissInventaireEntities.Instance.AtbDataTest.ToList();
            foreach (var DataTest in inv)
            {
                sw.WriteLine(string.Format("\"{0}\",\"{1}\",\"{2}\",\"{3}\",\"{4}\",\"{5}\",\"{6}\",\"{7}\",\"{8}\"",
                    DataTest.Code_materiel,
                    DataTest.Num_serie,
                    DataTest.Categorie,
                    DataTest.Modele,
                    DataTest.Marque,
                    DataTest.Statut,
                    DataTest.Date_inventaire,
                    DataTest.Date_installation,
                    DataTest.Localisation_complet));
            }
            Response.Write(sw.ToString());
            Response.End();
        }


        //public ActionResult Submit(IEnumerable<HttpPostedFileBase> files)
        //{
        //    if (files != null)
        //    {
        //        string fileName;
        //        string filepath;
        //        string fileExtension;

        //        foreach (var f in files)
        //        {
        //            //Set file details.
        //            SetFileDetails(f, out fileName, out filepath, out fileExtension);


        //                f.SaveAs(Server.MapPath(@"d:\"));

        //                //Read Data From ExcelFiles.
        //                ReadDataFromExcelFiles(@"d:\");

        //        }
        //    }
        //    return RedirectToAction("RapportBien", "Admin");
        //}

        //private static void SetFileDetails(HttpPostedFileBase f, out string fileName, out string filepath, out string fileExtension)
        //{
        //    fileName = Path.GetFileName(f.FileName);

WebApp/Views/ImportExport/Cipherlab.cshtml
@model IEnumerable<Domain.Cipherlab>



<!-- Start Row -->
<div class="row">
    <!-- Start Panel -->
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-title">

            </div>
            <div class="panel-body table-responsive">
                <table id="example0" class="table display">
                    <thead>
                        <tr>
                            <th>Code</th>
                            <th>Qte</th>
                        
                            <th>Action</th>
                        </tr>
                    </thead>

                    <tfoot>
                        <tr>
                            <th>Code</th>
                            <th>Qte</th>

                            <th>Action</th>
                        </tr>
                    </tfoot>

                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td class="center">@item.Code</td>
                                <td class="center">@item.Qte</td>
                              
                                <td>

                                    <a href="@Url.Action("Edit", new { id = item.ID })">&nbsp;<i class="fa fa-edit" title="Modifer"></i></a>
                                    <a href="@Url.Action("Delete", new { id = item.ID })">&nbsp;&nbsp;<i class="fa fa-trash" title="Effacer"></i></a>
                                </td>

                            </tr>


                        }
                    </tbody>
                </table>
                <br />

            </div>
        </div>
    </div>


</div>





<script>
    $(document).tooltip();
</script>

WebApp/Views/ImportExport/Create1.cshtml
@model IEnumerable<Domain.AtbDataTest>

@{
    List<Domain.AtbDataTest>
      atb = (List<Domain.AtbDataTest>
          )HttpContext.Current.Session["Tesst"];

}

<div class="row">
    <!-- Start Panel -->
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-title">
                Liste des Biens
            </div>
          
            <div class="panel panel-default">
                <div class="panel-body table-responsive">
                    <table id="example0" class="table display">
                        <thead>
                            <tr>
                                <th>Code Materiel </th>
                                <th>Num Serie </th>
                                <th>Categorie</th>
                                <th>Modele</th>
                                <th>Marque</th>
                                <th>Statut </th>
                                <th>Fin Garantie </th>
                                <th>Localisation </th>
                                <th>Entite Dernier</th>
                                <th>Date Inventaire</th>
                                <th>Date Installation</th>
                                <th>Localisation Complet</th>
                                <th>Entite Complet</th>
                                <th>Action</th>


                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in atb)
                            {
                                <tr class="odd gradeX">

                                    <td>@item.Code_materiel</td>
                                    <td>@item.Num_serie</td>
                                    <td>@item.Categorie</td>
                                    <td>@item.Modele</td>
                                    <td>@item.Marque</td>
                                    <td>@item.Statut</td>
                                    <td>@item.Fin_garantie</td>
                                    <td>@item.Localisation_dernier</td>
                                    <td>@item.Entite_dernier</td>
                                    <td>@item.Date_inventaire</td>
                                    <td>@item.Date_installation</td>
                                    <td>@item.Localisation_complet</td>
                                    <td>@item.Entite_complet</td>
                                    <td>
                                        <a href="@Url.Action("DetailsBien", new { id = item.id })">&nbsp;&nbsp;<i class="fa fa-folder-open" title="Details"></i></a>
                                    </td>
                                </tr>


                            }
                        </tbody>
                    </table>

                    <br /><p>





                    </p>
                    <br /><p>
                        @Html.ActionLink("Ajouter un nouveau Bien", "CreateBien")


                    </p>

                </div>
            </div>
        </div>


    </div>
</div>
<script>
    $(document).tooltip();
</script>

WebApp/Views/ImportExport/ImportTxt.cshtml
<div class="inner">
    <!-- Start Row -->
    <div class="row">
        <!-- Start Panel -->
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-title">
                    Joindre Un Fichier
                </div>
                <div class="panel-body table-responsive">
                    <div id="div-1" class="accordion-body collapse in body">

                        @using (Html.BeginForm("ImportTxt", "ImportExport", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            <div class="text-danger">@Html.Raw(ViewBag.Error)</div>
                            <div class="form-horizontal">
                                <table class="display" cellspacing="0" width="100%">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <input type="file" id="fileToUpload" name="file" />
                                            </td>
                                            <td align="right" colspan="2">
                                                <input type="submit" class="btn btn-default" value="Charger le fichier" />
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>

                        }


                    </div>
                </div>
            </div>
        </div>


    </div>
</div>

WebApp/Views/ImportExport/Index.cshtml
<div class="inner">
    <!-- Start Row -->
    <div class="row">
        <!-- Start Panel -->
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-title">
                    Joindre Un Fichier
                </div>
                <div class="panel-body table-responsive">
                    <div id="div-1" class="accordion-body collapse in body">
                       
                        @using (Html.BeginForm("SaveUploadedFile", "ImportExport", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                          <div class="text-danger">@Html.Raw(ViewBag.Error)</div>  
                            <div class="form-horizontal">
                                 <table class="display" cellspacing="0" width="100%">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <input type="file" id="fileToUpload" name="file" />
                                            </td>
                                            <td align="right" colspan="2">
                                                <input type="submit" class="btn btn-default" value="Charger le fichier" />
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>

                        }


                    </div>
                </div>
            </div>
        </div>


    </div>
</div>

WebApp/Views/ImportExport/Succes.cshtml
<html>
<head>

    <body>

        <table>

            <tr>
                <th>Nom</th>
                <th>Prenom</th>
            </tr>


            @foreach (var p in ViewBag.list)
            {

                <tr>
                    <td>@p.Code_materiel </td>
                    <td>@p.Num_serie</td>
                </tr>

            }
        </table>
    </body>
</head>

</html>